### ISSUE TITLE
Uncaught ReferenceError: keyIsDown is not defined

### ISSUE THREAD

**Issue by Zaptronic** [molleindustria/p5.play#3] opened 2015-07-22 16:02 UTC
I get errors when using the key methods.

I tried one of your examples:
```js
if (keyWentDown("x") || mouseWentDown(LEFT)) {
  asterisk.velocity.y = -JUMP;
}
```

but it gives me this error message in the console: `Uncaught ReferenceError: keyIsDown is not defined`

**Comment by toolness** [comment] 2015-10-31 20:04
Hmm, [`keyIsDown()`](http://p5js.org/reference/#/p5/keyIsDown) is a p5.js function--are you including that in your web page? Also, it looks like p5.play doesn't yet support p5.js's instance mode (#12), so you might have to disable that if you're using it.

**Comment by toolness** [comment] 2016-01-31 15:06
Hmm I'm unable to reproduce this bug, so I'm going to close this issue. Feel free to re-open it if you can provide further details on how to replicate it.

**Closed by toolness** 2016-01-31 15:06 UTC
