### ISSUE TITLE
Incorrect bouncing behaviour due to incorrect tunneling detection

### ISSUE THREAD

**Issue by jmmcd** [molleindustria/p5.play#214] opened 2022-04-26 14:33 UTC
Cross-posted from StackExchange: https://stackoverflow.com/questions/72006039/incorrect-bouncing-behaviour-in-p5js-play-library

I'm doing a simple bouncing balls demo, with one large ball whose mass in `play` is given by $\pi r^2$. The basic physics looks right to me. But after a few seconds, the large ball starts to jump large distances when struck by a small ball. 

Here's my complete code: https://editor.p5js.org/jmmcd/sketches/BMPtPY098

It seems like a bug in the collision/bounce code. But my code is conceptually the same as https://molleindustria.github.io/p5.play/examples/index.html?fileName=collisions4.js, which doesn't have this problem.

**Comment by quinton-ashley** [comment] 2022-05-03 01:13
possible duplicate of #191 

Try using a for loop to add the displacement for all circles

**Comment by quinton-ashley** [comment] 2022-05-03 23:17
@jmmcd hmm okay thanks for trying, I will look into this!

**Comment by quinton-ashley** [comment] 2022-05-04 19:39
@jmmcd I tried having the big circle displace all the little circles and the little circles all bounce of each other.

https://editor.p5js.org/quinton-ashley/sketches/1JE8MmV04

It still doesn't look perfect but probably close to what you want. Let me know what you think :)

**Comment by quinton-ashley** [comment] 2022-05-04 21:16
The problem is the code for tunneling detection in p5.play is wrong. This code should test if one object is going so fast that it would get to the other side of an object it is supposed to bounce off. However it's triggering a lot even when this isn't the case. The code for managing tunneling is also horrible and doesn't even care that these are circles (that's why you'll see circles stuck on an invisible square when running the sketch I sent.

**Comment by jmmcd** [comment] 2022-05-05 09:23
Thanks. Yes, the tunneling makes sense as an explanation. This suggests that keeping all velocities low might help to avoid the problem.

The sketch you sent does indeed help to make the point that the sketch is intended to make (it's about the so-called arrow of time). Thank you very much for this! But yes, even apart from the invisible square, it would be better to have a simple and consistent behaviour of all particles, ie every particle bounces every other.

**Comment by quinton-ashley** [comment] 2022-05-05 14:23
@jmmcd That would be a logical conclusion but I don't even think that would work since the detection code is so bad. For now I just removed it so you can try it out.

Here's the example with p5.play v2.1.3 with tunneling detection issues:

https://editor.p5js.org/quinton-ashley/sketches/OfNEXge9V

Here's the example with the latest version of p5.play (v2.2.2):

https://editor.p5js.org/quinton-ashley/sketches/OfNEXge9V

p5.play is also missing important physics detection for things like if the big circle squishes a little circle against the wall. I also think the total momentum should stay the same in this example right? But it doesn't. You should try this p5.js version of planck.js it has a super accurate and fast physics simulation! I'm considering gutting p5.play's physics in favor of using this behind the scenes every time a sprite is created.

https://editor.p5js.org/Bobcook47/sketches/S2RqS8ie-

https://github.com/bobcgausa/cook-js

**Comment by quinton-ashley** [comment] 2022-05-06 05:15
This is still far from an accurate physics simulation but now it only uses `bounce` functions, not `displace` (which made the little circles look like super light liquid particles that the large circles could push aside with ease). What should happen here I think is that the big circles lose momentum to the little circles, which gain a LOT of momentum, but the total momentum should be constant.

I mostly fixed the tunneling issues by using bounding circles instead of bounding boxes. I used thin walls to test it.

https://editor.p5js.org/quinton-ashley/sketches/AirXZvLKr

The sprites stop updating in this example if a ball escapes the wall. This is the most I can do with the physics implemented in p5.play.

There are other issues with the physics that I want to solve by using planck.js such as collision detection on rotated rectangles #142 + #205 and group displacement #191 

Stay tuned!

**Closed by quinton-ashley** 2022-05-06 05:15 UTC
Labels: bug

**Comment by quinton-ashley** [comment] 2022-05-06 13:26
thanks!
