### ISSUE TITLE
sprite.height

### ISSUE THREAD

**Issue by ltejedor** [molleindustria/p5.play#6] opened 2015-08-24 16:20 UTC
Not sure if it's an issue or on purpose, but sprite.height returns its position.y, not its actual height.

**Comment by toolness** [comment] 2016-01-31 15:26
Hmm, can you provide an example for this? I'm finding that the following sketch seems to work as expected:

```js
var sprite;

function setup() {
  createCanvas(300, 300);
  sprite = createSprite(100, 100);
  sprite.velocity.y = 1; 
}

function draw() {
  background(255);
  drawSprites();

  textSize(12);
  fill('black');
  text("height: " + sprite.height +
       " position.y: " + sprite.position.y, 10, 30);
}
```

**Comment by toolness** [comment] 2016-01-31 15:34
I also tried it with images and things still seem to work:

```js
var sprite, img;

function preload() {
  img = loadImage("examples/assets/asterisk.png");
}

function setup() {
  createCanvas(300, 300);
  sprite = createSprite(100, 100);
  sprite.addImage('asterisk', img);
  sprite.velocity.y = 1; 
}

function draw() {
  background(255);
  drawSprites();

  textSize(12);
  fill('black');
  text("height: " + sprite.height +
       " position.y: " + sprite.position.y, 10, 30);
}
```

**Comment by toolness** [comment] 2016-01-31 15:37
Since I can't reproduce this issue, I'm going to close it. But if anyone can provide an example that replicates the problem, feel free to reopen it!

**Comment by molleindustria** [comment] 2016-01-31 15:38
The height is calculated differently whether the sprite has is a placeholder square, image or an animation so it would be useful to know in what circumstances that happens.

**Closed by toolness** 2016-01-31 15:37 UTC
