### ISSUE TITLE
Rotate collider along with sprite

### ISSUE THREAD

**Issue by theneuetimes** [molleindustria/p5.play#173] opened 2018-12-19 18:22 UTC
I want to have my sprite rotated at a slight angle, and I need a collider on it. I can do this:
```js
let sprite = createSprite(x, y, width, height);
sprite.setCollider("rectangle", 0, 0, width, height);
```

But this doesn't rotate the collider, just makes it larger.
![result](https://i.imgur.com/J54w4TW.jpg)

What I need is a collider matching the sprite, like here:
![expected result](https://i.imgur.com/cd1bmmB.jpg)

The `setCollider` function seems to ignore the rotation too.

Is it an error on my end or the library?

**Comment by SaintPepsi** [comment] 2018-12-26 12:54
Hi, I noticed your post on this dead repository and I thought i'd give it a shot at helping out.

From what i know, `rectangle` colliders don't rotate, what you can rotate however is a `polygon` data set, there's actually a p5 library called p5.collide2D [Repository](https://github.com/bmoren/p5.collide2D) which contains functions like : `collidePolyPoly()`

If you don't know what a poly is, it's basically an array with `x` and `y` values to determine the lines that make up the collider.

Hope that helped.

**Comment by quinton-ashley** [comment] 2022-05-03 03:16
duplicate of #142

**Closed by quinton-ashley** 2022-05-03 03:16 UTC
Labels: enhancement
